lok/PAB-3
CNDvn/ParkingApp-BE pull request #14
Opened 2022-01-29 12:04 UTC by DQLok

signUp 
change entity user, customer, business

2022-01-29 15:11 UTC, CNDvn requested changes

2022-01-29 15:11 UTC, CNDvn commented on src/exception/catch-all-exception.filter.ts
> +    console.log(exception);
??. nên xóa log này

2022-01-29 15:11 UTC, CNDvn commented on src/main/auth/jwt/jwt.strategy.ts
> +    console.log(payload);
nên xóa cái này

2022-01-29 15:11 UTC, CNDvn commented on src/main/base/base.entity.ts
> +  // public updatedBy: string;
tầm bậy tầm bạ, dám sửa code chuẩn à. để lại như cữ nghe chưa

2022-01-29 15:11 UTC, CNDvn commented on src/main/user/dto/user.create.dto.ts
> +  public status: string;
không nên để status cho phía client xét. nên xóa field status đi. sửa tên file luôn nha

2022-01-29 15:11 UTC, CNDvn commented on src/main/business/dto/business.signup.dto.ts
> +export class BusinessSignUpDto extends UserCreateDto {}
sửa lại tên file là business-signup.dto.ts

2022-01-29 15:11 UTC, CNDvn commented on src/main/role/role.controller.ts
> +  @Public()
bậy bạ, xóa cái này đi

2022-01-29 15:11 UTC, CNDvn commented on src/main/role/role.controller.ts
> +    console.log(roleCreateDTO);
xóa log đi

2022-01-29 15:11 UTC, CNDvn commented on src/main/user/user.profile.ts
> +      // );
cmt vỗ nghĩa, xóa đi

2022-01-29 15:11 UTC, CNDvn commented on src/main/user/user.repository.ts
> +    user.status = data.status;
để status mặc định khi tạo là inactive

2022-01-29 15:11 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +    );
trước khi làm điều này thì check xem user bị undefine không, nếu có thì throw exception  trước khi check isMatch

2022-01-30 01:00 UTC, CNDvn approved these changes

2022-01-30 02:25 UTC, baosphoa0403 approved these changes

2022-01-30 13:24 UTC, merged