Bao/PAB 19
CNDvn/ParkingApp-BE pull request #17
Opened 2022-02-06 09:31 UTC by baosphoa0403

Develop Create Parking feature

2022-02-06 14:54 UTC, CNDvn requested changes

2022-02-06 14:54 UTC, CNDvn commented on src/main/parking/parking.repository.ts
> +        business: businessOwner,
thêm value cho field createBy

2022-02-06 14:54 UTC, CNDvn commented on src/main/parking/parking.service.ts
> +  async creatParking(
createParking

2022-02-07 03:19 UTC, DQLok approved these changes

2022-02-07 03:19 UTC, DQLok commented on src/validator/isBefore.validation.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
no disable

2022-02-07 07:57 UTC, CNDvn approved these changes

2022-02-07 08:06 UTC, merged