api delete parking (pending)
CNDvn/ParkingApp-BE pull request #24
Opened 2022-02-07 14:24 UTC by thahvii

Design a API for delete a parking

2022-02-07 14:36 UTC, DQLok commented on src/main/parking/parking.controller.ts
> +  @Delete('/:id')
thiếu role, apiResponse

2022-02-08 01:30 UTC, CNDvn requested changes
Merge dev rồi check code lại nha, @Getuser() user có type là User rồi

2022-02-08 15:14 UTC, baosphoa0403 requested changes

2022-02-08 15:14 UTC, baosphoa0403 commented on src/main/parking/parking.controller.ts
> +@Controller('parkings')
Parkings

2022-02-17 14:09 UTC, CNDvn requested changes

2022-02-17 14:09 UTC, CNDvn commented on src/main/parking/parking.service.ts
> +            parking.status == 'inActive';
parking.status == 'inActive' => ? . toán tử == dùng để so sánh chứ đâu để update. và không hard cứng chuỗi inActive mà hãy gọi enum là StausEnum để lấy status

2022-02-20 16:36 UTC, CNDvn approved these changes

2022-02-20 16:37 UTC, baosphoa0403 approved these changes

2022-02-20 16:37 UTC, merged