lok/PAB-11
CNDvn/ParkingApp-BE pull request #27
Opened 2022-02-08 02:57 UTC by DQLok

features user

2022-02-08 03:22 UTC, baosphoa0403 approved these changes, later dismissed

2022-02-08 03:33 UTC, CNDvn requested changes

2022-02-08 03:33 UTC, CNDvn commented on src/main/user/user.controller.ts
> +  }
thiếu Automap, sai role

2022-02-08 03:57 UTC, baosphoa0403 approved these changes, later dismissed

2022-02-08 03:58 UTC, CNDvn approved these changes, later dismissed

2022-02-09 05:59 UTC, CNDvn approved these changes

2022-02-09 08:56 UTC, baosphoa0403 approved these changes

2022-02-09 08:57 UTC, merged