reset and change password
CNDvn/ParkingApp-BE pull request #30
Opened 2022-02-08 09:29 UTC by NguyennKhoaa

reset and change password

2022-02-08 09:38 UTC, baosphoa0403 requested changes

2022-02-08 09:38 UTC, baosphoa0403 commented on src/main/auth/dto/changePasswordDto.ts
> +  confirmPassword: string;
Not check empty

2022-02-08 09:38 UTC, baosphoa0403 commented on src/main/auth/dto/resetPasswordDto.ts
> +}
Not check empty

2022-02-08 09:38 UTC, baosphoa0403 commented on src/main/auth/dto/changePasswordDto.ts
> +  password: string;
https://stackoverflow.com/questions/60451337/password-confirmation-in-typescript-with-class-validator
recommend you create class or decorator confirm password

2022-02-09 02:58 UTC, CNDvn requested changes

2022-02-09 02:58 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +  }
login không hiểu

2022-02-09 02:58 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +    }
tìm bằng username sao lại throw lỗi not found phone

2022-02-11 14:44 UTC, baosphoa0403 requested changes

2022-02-11 14:44 UTC, baosphoa0403 commented on src/main/auth/auth.controller.ts
> +  @Post('/changePassword')
Please description response

2022-02-11 14:44 UTC, baosphoa0403 commented on src/main/auth/auth.controller.ts
> +  @Post('/verifyOTP')
same above

2022-02-11 14:44 UTC, baosphoa0403 commented on src/main/auth/auth.service.ts
> +    }
Thinking about customs check

2022-02-11 14:44 UTC, baosphoa0403 commented on src/main/auth/dto/changePasswordDto.ts
> +  @IsNotEmpty()
Please use IsNotBlank

2022-02-11 14:51 UTC, CNDvn requested changes
logic có vẻ không hay. nếu reset password mà send opt thì làm như sau. gửi otp về cho người dùng nếu người dùng nhập otp chính xác thì mở form change password để người dùng tự nhập password. Nếu đã dùng việc tự tạo password mặc định để send về cho người dùng rồi thì không cần send otp làm gì nữa nếu làm cách này thì khuyễn khích vì DỄ

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  }
sao lại tạo end point này

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  @Public()
trên controller có public tổng rồi nền chỗ này ko cần nữa => xóa đi

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  @Public()
xóa đi

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  @Public()
như trên

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  @Public()
như trên

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.controller.ts
> +  @Public()
như trên

2022-02-11 14:51 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +      phoneNumberVerifyCodeExpire: new Date(),
phải thêm 5 phút vô nữa mới đúng chứ nhề

2022-02-14 08:52 UTC, CNDvn approved these changes, later dismissed

2022-02-14 08:52 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +    const sendOTP = await this.sharedService.generateOtp();
sendOTP không hợp lệ

2022-02-14 13:34 UTC, baosphoa0403 approved these changes

2022-02-14 13:57 UTC, DQLok approved these changes

2022-02-14 13:58 UTC, merged