Bao/pab 20
CNDvn/ParkingApp-BE pull request #37
Opened 2022-02-11 17:06 UTC by baosphoa0403

###[PAB-20] develop create slot for a parking
##Upload parking
##Upload avartar user
##Fix automapper user profile

2022-02-13 13:21 UTC, CNDvn requested changes

2022-02-13 13:21 UTC, CNDvn commented on src/main/car/car.controller.ts
>    }
cục này sao để public vậy

2022-02-13 13:21 UTC, CNDvn commented on src/main/parking-slot/parking-slot.controller.ts
> +@ApiTags('ParkingSlot')
thiếu s để chỉ số nhiều

2022-02-13 13:21 UTC, CNDvn commented on src/main/parking-slot/parking-slot.controller.ts
> +@Roles(RoleEnum.BUSINESS)
trong controller này có vài end-point có thể để cho user role customer vào. ví dụ sau này sẽ có end-point cho customer lấy các slot trống trong 1 parking. Nên set role cho từng end-point thay vì set cho tổng các end-point

2022-02-13 13:21 UTC, CNDvn commented on src/main/parking-slot/parking-slot.controller.ts
> +  @Post('/createParkingCustom/:idParking')
![image](https://user-images.githubusercontent.com/63216927/153754986-7164d844-0941-4037-88ea-fd3cf77a95f8.png)
xem ảnh, end-point này ý là cho người dùng đặt tên cho 1 slot chứ ko phải là chọn prefixName

2022-02-14 07:13 UTC, CNDvn approved these changes

2022-02-14 07:40 UTC, DQLok approved these changes

2022-02-14 07:41 UTC, merged