Crud Promotion
CNDvn/ParkingApp-BE pull request #39
Opened 2022-02-14 08:50 UTC by thahvii

Crud Promotion

2022-02-15 02:11 UTC, baosphoa0403 commented on src/main/parking/parking.controller.ts
> +@ApiTags('Parking')
Please change Parking -> Parkings

2022-02-15 02:12 UTC, baosphoa0403 commented on src/main/parking/parking.controller.ts
> +  @Roles(RoleEnum.BUSINESS)
Why two decorator roles

2022-02-15 02:13 UTC, baosphoa0403 commented on src/main/promotion/dto/promotion-create.dto.ts
> +    @Validate(Max(15))
I remember Max(15) not @Validate(Max(15)) read documents control + f search Max() : https://github.com/typestack/class-validator#validation-errors

2022-02-15 02:15 UTC, baosphoa0403 commented on src/main/promotion/dto/promotion-create.dto.ts
> +        type: String, description: 'Percent'
percent: number why you description api string ??

2022-02-15 02:35 UTC, baosphoa0403 requested changes

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/dto/promotion-create.dto.ts
> +
Please remove spacing

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/dto/promotion-create.dto.ts
> +
same above

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/dto/promotion-create.dto.ts
> +    public status: string;
I think you don't send status instead of you set status in back end

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/promotion.controller.ts
> +  @Post()
Please add role have create promotion

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/promotion.dto.ts
> +
please remove spacing

2022-02-15 02:35 UTC, baosphoa0403 commented on src/main/promotion/promotion.service.ts
> +    }
Please explain logic code here

2022-02-15 02:45 UTC, DQLok requested changes

2022-02-15 02:45 UTC, DQLok commented on src/main/promotion/promotion.controller.ts
> +
remove spacing

2022-02-15 02:45 UTC, DQLok commented on src/main/promotion/promotion.controller.ts
> +
remove spacing

2022-02-15 02:45 UTC, DQLok commented on src/main/promotion/promotion.controller.ts
> +
remove spacing

2022-02-15 02:45 UTC, DQLok commented on src/main/promotion/promotion.repository.ts
> +
remove spcaing

2022-02-17 14:08 UTC, CNDvn requested changes

2022-02-17 14:08 UTC, CNDvn commented on src/main/parking/parking.controller.ts
> +@Controller('Parkings')
thay Parkings thành parkings ở controller. chữ P viết thường vì đây là đường dẫn nên mình dùng cách viết camelcase

2022-02-17 14:08 UTC, CNDvn commented on src/main/promotion/promotion.controller.ts
> +  }
hàm này có ý gì. tại sao dev promotion lại có thằng delete user

2022-02-17 14:08 UTC, CNDvn commented on src/main/promotion/promotion.service.ts
> +        }
không hiểu logic, giải ngố hộ

2022-02-17 14:08 UTC, CNDvn commented on src/main/promotion/promotion.controller.ts
> +  }
thiếu bước kiểm tra xem req gửi lên có chính xác là người tạo ra promotion đó không

2022-02-17 14:08 UTC, CNDvn commented on src/main/promotion/promotion.controller.ts
> +  }
như trên

2022-02-20 15:44 UTC, baosphoa0403 approved these changes

2022-02-20 15:44 UTC, CNDvn approved these changes

2022-02-20 16:26 UTC, DQLok approved these changes

2022-02-20 16:26 UTC, merged