[PAB-32] refactor signup OTP
CNDvn/ParkingApp-BE pull request #47
Opened 2022-02-15 13:56 UTC by NguyennKhoaa

2022-02-15 14:09 UTC, baosphoa0403 submitted a review, later dismissed

2022-02-17 14:07 UTC, CNDvn requested changes

2022-02-17 14:07 UTC, CNDvn commented on src/main/auth/auth.service.ts
> +      status: StatusEnum.ACTIVE,
verify signUp là gửi mã otp về số điện thoại người dùng đăng ký nên khi verify thành công thì đồng thời cột phoneNumberConfirmed cũng phải từ false thành true (tức là sđt đã được xác minh)

2022-02-20 06:53 UTC, DQLok commented on src/main/customer/customer.repository.ts
> +    // await this.smsService.sendSms(user.phoneNumber, otp.toString());
clean code

2022-02-20 15:34 UTC, NguyennKhoaa commented
review lại

2022-02-20 15:34 UTC, CNDvn approved these changes, later dismissed

2022-02-20 15:43 UTC, baosphoa0403 approved these changes, later dismissed

2022-02-20 16:07 UTC, CNDvn approved these changes

2022-02-20 16:10 UTC, DQLok approved these changes

2022-02-20 16:11 UTC, merged