[PAB-26] crud parking service
CNDvn/ParkingApp-BE pull request #50
Opened 2022-02-19 09:12 UTC by NguyennKhoaa

2022-02-19 09:21 UTC, CNDvn requested changes

2022-02-19 09:21 UTC, CNDvn commented on src/main/service/service.service.ts
> +        'canonot add new service',
cannot not canonot

2022-02-20 06:49 UTC, DQLok commented on src/main/service/dto/service-create.dto.ts
> +export class ServiceCreateDto {
should rename ServiceParking for all Module

2022-02-20 06:49 UTC, DQLok commented on src/main/service/dto/service-create.dto.ts
> +  @ApiProperty({ type: String, description: 'description' })
should insert space between fields

2022-02-20 06:49 UTC, DQLok commented on src/main/service/service.controller.ts
> +  @Get('/:parkingId')
id not parkingId

2022-02-20 06:49 UTC, DQLok commented on src/main/service/service.controller.ts
> +    return 'success';
processing code should write in service.ts shouldn't write in controller

2022-02-20 06:49 UTC, DQLok commented on src/main/service/service.service.ts
> +export class ServiceService extends BaseService<Service> {
rename right now

2022-02-20 06:49 UTC, DQLok commented on src/main/service/service.service.ts
> +    // }
clean code

2022-02-20 15:46 UTC, CNDvn requested changes

2022-02-20 15:46 UTC, CNDvn commented on src/main/service/dto/service-create.dto.ts
> +  public parkingId: string;
Please validation

2022-02-20 15:46 UTC, CNDvn commented on src/main/service/service.entity.ts
Please add automap field

2022-02-20 15:46 UTC, NguyennKhoaa commented
clean code

2022-02-20 16:00 UTC, CNDvn requested changes

2022-02-20 16:00 UTC, CNDvn commented on src/main/service/service.service.ts
> +    const parking = await this.parkingService.findById(serviceDto.parkingId);
chưa check xem người gửi req có thật sự là chủ của parking mà họ gửi lên hay không

2022-02-20 16:00 UTC, CNDvn commented on src/main/service/service.controller.ts
> +  @Roles(RoleEnum.BUSINESS)
nên để public

2022-02-20 17:01 UTC, baosphoa0403 approved these changes

2022-02-20 17:02 UTC, NguyennKhoaa commented
fix

2022-02-20 17:02 UTC, CNDvn approved these changes

2022-02-20 17:02 UTC, merged