Create Wallet , Update Wallet , Get Wallet Me
CNDvn/ParkingApp-BE pull request #82
Opened 2022-03-04 17:08 UTC by baosphoa0403

2022-03-04 17:14 UTC, DQLok approved these changes, later dismissed

2022-03-05 06:22 UTC, CNDvn requested changes

2022-03-05 06:22 UTC, CNDvn commented on src/main/wallet/wallet.controller.ts
> +
nên để role admin hoặc không cần end-point này

2022-03-05 09:13 UTC, baosphoa0403 commented on src/main/wallet/wallet.controller.ts
> +
để đỡ á :v
để insert ✌️ V

2022-03-05 09:28 UTC, CNDvn approved these changes

2022-03-05 09:30 UTC, lpduy2k approved these changes

2022-03-05 09:30 UTC, merged